---
image:
  name: "hashicorp/packer"

before_script:
   - pwd

stages:
  - validate
  - build

validate:
  stage: validate

  script:
    - validate -syntax-only packer.json

build:
  stage: build
  script:
    - pwd
    - build packer.json
