---
image:
  name: "hashicorp/terraform:0.12.29"

  entrypoint:
   - "/usr/bin/env"
   - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

before_script:
   - sudo apt-get update && sudo apt-get install -y unzip
   - wget https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip
   - unzip packer_1.6.0_linux_amd64.zip
   - mv packer /usr/local/bin/
   - pwd
   - packer -v

stages:
  - validate
  - build

validate:
  stage: validate

  script:
    - packer validate -syntax-only packer.json 

build:
  stage: build

  script:
    - packer build packerfile.json
