---
image:
  name: "alpine"
  entrypoint:
   - "/usr/bin/env"
   - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

before_script:
   - apt update && apt install -y wget unzip
   - wget https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip
   - unzip packer_1.6.0_linux_amd64.zip
   - cp packer /usr/local/bin/
   - pwd
   - packer -v

stages:
  - build

build:
  stage: build
  script:
    - packer build packer.json
